### PR TITLE
Updates user profile translation for LIBBO-LAW to MXFEE-LAW

### PR DESCRIPTION
**Pull request by shelleydoljack**
@jgreben quick fix to library_patron.xsl. I tested on morison and would like to move to bodoni today.

### CODE REVIEW

**Comment by dlrueda** [comment]
Are we sure that ALL LIBBO-LAW users are all supposed to have MXFEE-LAW?

**Comment by shelleydoljack** [comment]
@dlrueda it's users with "affiliate" in the first affiliation field and LIBBO-LAW as the code. That's the only place we're assigning anything with a LIBBO-LAW code. Also, we've already merged the TLS upgrade stuff into the master branch so I'm not sure anymore if we want to merge this PR into master and update master on Bodoni today.

**Comment by dlrueda** [comment]
I just didn't get a clear understanding from the emails back and forth with Sarah that users with LIBBO-LAW with first affiliation "affiliate" ALWAYS need to be MXFEE-LAW.  Perhaps that IS the case, but can you double-check with Sarah?  Perhaps it is true that any card issued by Law Lib (I think that's where LIBBO-LAW comes from) needs to be MXFEE-LAW.  But I'd like that confirmed with Sarah before proceeding.

**Comment by shelleydoljack** [comment]
I'm going to close this pull request since we're not ready yet for it to be merged.

**Comment by shelleydoljack** [comment]
Sarah confirmed with the ID card office the aff code LIBBO-LAW is for Law Alumni and therefore should always get MXFEE-LAW profile. @jgreben @dlrueda let's plan to merge this and deploy to production this weekend for the TLS upgrade.

**Pull request merged**
