### PR TITLE
Make term for Winter 17 instead of 16 

### PR DESCRIPTION
**Pull request by jgreben**
(which matches the code in the registry coded year, e.g. 1164)

@shelleydoljack can you merge this when you get a chance. The registry data has 1164 for the coded term, but I think this should translate to Winter 17 not 16. Otherwise it makes no sense that we would be harvesting a course from last year. I guess that the code is generated as 1164 because it is harvested this year for a quarter that happens next year.

### CODE REVIEW

**Comment by dlrueda** [comment]
I have this in some documentation for course formatting:
#course format notes:
#The classID is in this format:
#1032-aa-214a-01
#The first part of the code: 1032<br> breaks down to: 1 03 2
#1 = first century using People Soft
#03 = 2002-2003 school year
#2 = autumn, 4 = winter, 6 = spring, 8 = summer

So, I think this agrees with what Josh said.  Fall quarter (current quarter) for this academic year would be 1172, winter quarter (next quarter) 1174.  I assume we're harvesting courses for the current quarter, and that those are coded 1172?

**Comment by shelleydoljack** [comment]
I'm confused now. I looked at the data in /s/SUL/Harvester/out/course_harvest.out.201611141515 and there are course ID's for 1174 (the upcoming winter term). Yet our file that contains the harvested data for winter (/s/SUL/Harvester/include/courses/winter.reg.xml) only has 1164 as class ID's, thus only producing a courseXML_W16.xml file. 1174 should produce a courseXML_W17.xml file.

**Comment by jgreben** [comment]
Ok, it looks like I was only grabbing the Winter courses from last year in the harvested registry xml. @shelleydoljack take a look at the changed files now. This should jive with wheat Grace said in the HelpSU message. Also, of you look at a course_harvest.out file, you will see the 1174 courses in there. We will have to do another complete rerun of all the harvested file. It will take a long time to complete. I will kick it off this morning.

**Comment by jgreben** [comment]
I will also checkout this branch on bodoni and kick off the full run so I can starting it 3 hours ahead of you...

**Comment by shelleydoljack** [comment]
@jgreben This looks much better. I checked the academic calendar and Autumn and Winter quarters are the only ones where we will need to use "this year" and "next year" in order to determine courses to select from the harvested data. I will check the files built once the process finishes.

**Pull request merged**
